# Generated by Django 4.0.5 on 2022-07-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('college', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=150)),
                ('division', models.CharField(max_length=50)),
            ],
        ),
    ]
