# Generated by Django 4.0.5 on 2022-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_college_alter_student_phone_alter_student_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
